# -*- coding: utf-8 -*-
"""App .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zf0kz8oLU9B6lNLOgkJMJW7Vp3CesT9
"""

# 1 improtar librerias
import streamlit as st
import pandas as pd

st.title("Mi primera aplicacion en streamlit")